name: download-and-commit-microdados

on:
  schedule:
    - cron:  '0 */2 * * *'

jobs:
  run:
    name: Download and Commit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install requirements
      run: sudo apt-get install -y --no-install-recommends fdupes

    - name: Download files
      run: ./download-microdados.sh

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Enderson Maia
        author_email: endersonmaia@gmail.com
        message: "update microdados files"
        add: "./sintomas/*.csv"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}